language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "pypy3"

before_install:
  - "export LIBGIT2=$VIRTUAL_ENV"
  - "wget https://github.com/libgit2/libgit2/archive/v0.22.0.tar.gz"
  - "tar xzf v0.22.0.tar.gz"
  - "cd libgit2-0.22.0/"
  - "cmake . -DCMAKE_INSTALL_PREFIX=$LIBGIT2"
  - "make"
  - "make install"
  - "export LDFLAGS=\"-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS\""
  - "cd ../"

install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

script: "py.test --pep8 --flakes --clearcache"
